[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E","F","I","UP"]
ignore = []
exclude = ["venv",".venv","migrations","alembic"]
target-version = "py311"

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-q"
